// Locators covered by both parity tests: the engine's matching and the AST -> Playwright mapping.
module.exports = [
  // roles and names
  "getByRole('link')", "getByRole('link', { name: 'Orders' })", "getByRole('link', { name: 'orders', exact: true })",
  "getByRole('button')", "getByRole('button', { name: 'Save' })", "getByRole('button', { name: 'Save profile' })",
  "getByRole('button', { name: 'Submit' })", "getByRole('button', { name: 'Reset' })",
  "getByRole('button', { name: 'Close' })", "getByRole('button', { name: 'Preferences' })", "getByRole('button', { name: 'Settings icon Preferences' })",
  "getByRole('button', { name: 'Before text' })", "getByRole('button', { name: 'More options' })", "getByRole('button', { name: /edit/i })",
  "getByRole('button', { name: 'Div button' })", "getByRole('button', { disabled: true })", "getByRole('button', { pressed: true })",
  "getByRole('button', { expanded: false })", "getByRole('button', { includeHidden: true })",
  "getByRole('textbox')", "getByRole('textbox', { name: 'First name' })", "getByRole('textbox', { name: 'Last name' })",
  "getByRole('textbox', { name: 'Middle name' })", "getByRole('textbox', { name: 'Email address' })", "getByRole('textbox', { name: 'Password' })",
  "getByRole('textbox', { name: 'Tell us about yourself' })", "getByRole('searchbox')", "getByRole('spinbutton')", "getByRole('slider')",
  "getByRole('combobox', { name: 'Country' })", "getByRole('checkbox')", "getByRole('checkbox', { checked: true })",
  "getByRole('checkbox', { name: 'Subscribe to updates' })", "getByRole('radio', { name: 'Pro plan', checked: true })",
  "getByRole('heading')", "getByRole('heading', { level: 2 })", "getByRole('heading', { name: 'Custom heading', level: 4 })",
  "getByRole('dialog')", "getByRole('dialog', { name: 'Edit order' })", "getByRole('dialog', { name: 'Confirm delete' })",
  "getByRole('dialog', { name: 'Edit order' }).getByRole('button', { name: 'Cancel' })",
  "getByRole('row')", "getByRole('row', { name: 'Order 1001' })", "getByRole('row', { name: 'Order 1002', exact: false }).getByRole('button')",
  "getByRole('cell')", "getByRole('columnheader')", "getByRole('rowheader')", "getByRole('table', { name: 'Order history' })",
  "getByRole('listitem').filter({ hasText: 'Pears' }).getByRole('button', { name: 'Remove' })",
  "getByRole('navigation', { name: 'Main' })", "getByRole('main')", "getByRole('banner')", "getByRole('contentinfo')",
  "getByRole('region')", "getByRole('region', { name: 'Orders' })", "getByRole('form')", "getByRole('form', { name: 'Profile' })",
  "getByRole('tab', { selected: true })", "getByRole('tablist').getByRole('tab')", "getByRole('switch', { checked: true })",
  "getByRole('checkbox', { checked: 'mixed' })", "getByRole('img')", "getByRole('img', { name: 'Company logo' })", "getByRole('presentation')",
  "getByRole('group')", "getByRole('group', { name: 'Billing' })", "getByRole('list')", "getByRole('paragraph')", "getByRole('status')",
  "getByRole('progressbar', { name: 'Upload progress' })", "getByRole('link', { name: 'Go to top' })", "getByRole('strong')",
  // text
  "getByText('Order 1001')", "getByText('Order 1002')", "getByText('Order 1002', { exact: true })", "getByText('order')",
  "getByText('Welcome back')", "getByText('Welcome back, Jane!')", "getByText('Contact support team')", "getByText(/support\\s+team/)",
  "getByText('Nested text')", "getByText('Hidden button')", "getByText('Save profile')", "getByText('Edit')", "getByText('Remove')",
  "getByText('Apples')", "getByText('More info')", "getByText(/^Pro/)",
  // labels, placeholders, alt, title, test ids
  "getByLabel('First name')", "getByLabel('First name *', { exact: true })", "getByLabel('Last name')", "getByLabel('Middle name')",
  "getByLabel('Email')", "getByLabel('Country')", "getByLabel('Subscribe')", "getByLabel('Pro plan')", "getByLabel('Card number')",
  "getByLabel('Quantity')", "getByLabel(/plan/)", "getByLabel('Profile')",
  "getByPlaceholder('Jane')", "getByPlaceholder('jane', { exact: true })", "getByPlaceholder('e')", "getByPlaceholder(/^Search/)",
  "getByAltText('logo')", "getByAltText('Company logo', { exact: true })", "getByTitle('Help')", "getByTitle('Password')",
  "getByTestId('save-draft')", "getByTestId('save')", "locator('[data-qa=\"discard\"]')",
  // css, xpath, chains, positions, filters
  "locator('button')", "locator('form input')", "locator('#first')", "locator('xpath=//li')",
  "getByRole('button').first()", "getByRole('button').last()", "getByRole('button').nth(3)", "getByRole('button').nth(-2)",
  "getByRole('row').filter({ hasText: 'Pending' })", "getByRole('row').filter({ hasNotText: 'Order' })", "getByRole('button').filter({ visible: true })",
  "getByRole('listitem').filter({ hasText: /apples/i })", "locator('section').getByText('strong')", "getByRole('dialog').getByRole('button').nth(1)"
];
